language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
env:
    - REDIS_HOST=localhost REDIS_PORT=6379
services:
    - redis-server
    - postgresql
before_script:
  - psql -c 'create database test-0x2048;' -U postgres
script:
    - pytest
    - flake8
notifications:
    email: false
