language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
env:
    - REDIS_HOST=localhost REDIS_PORT=6379
services:
    - redis-server
script:
    - pytest
    - flake8
notifications:
  webhooks:
    on_success: never
    on_failure: never
    on_cancel: never