version: 2
jobs:
  build:
    working_directory: ~/webserver
    docker:
      - image: circleci/python:3.6.4
        environment:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
      - image: redis
    steps:
      - checkout
      - run:
          name: "pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "install"
          command: |
            pip install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "test"
          command: |
            source venv/bin/activate
            pytest
