version: 2
jobs:
  build:
    working_directory: ~/webserver
    docker:
      - image: circleci/python:3.6.4
        environment:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            source venv/bin/activate
            pytest tests/unit/payment/test_confirm_payment.py::test_confirm_payment_success -s
