import os

# Public
ARCADE_ADDRESS = '0x6097038687bed106f87DB3fF9d96e71933526C98'
ARCADE_ABI = '[{"inputs": [], "stateMutability": "nonpayable", "type": "constructor"}, {"inputs": [{"internalType": "bytes32", "name": "gameId", "type": "bytes32"}], "name": "getHighscore", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"}, {"inputs": [{"internalType": "bytes32", "name": "gameId", "type": "bytes32"}], "name": "getJackpot", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"}, {"inputs": [{"internalType": "bytes32", "name": "gameId", "type": "bytes32"}, {"internalType": "address", "name": "addr", "type": "address"}], "name": "getPaymentCode", "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}], "stateMutability": "view", "type": "function"}, {"inputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}], "name": "highscores", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"}, {"inputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}], "name": "jackpots", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"}, {"inputs": [], "name": "owner", "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"}, {"inputs": [{"internalType": "bytes32", "name": "gameId", "type": "bytes32"}, {"internalType": "bytes32", "name": "paymentCode", "type": "bytes32"}], "name": "pay", "outputs": [], "stateMutability": "payable", "type": "function"}, {"inputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}, {"internalType": "address", "name": "", "type": "address"}], "name": "paymentCodes", "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}], "stateMutability": "view", "type": "function"}, {"inputs": [], "name": "price", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"}, {"inputs": [{"internalType": "uint8", "name": "v", "type": "uint8"}, {"internalType": "bytes32", "name": "r", "type": "bytes32"}, {"internalType": "bytes32", "name": "s", "type": "bytes32"}, {"internalType": "uint256", "name": "score", "type": "uint256"}, {"internalType": "bytes32", "name": "gameId", "type": "bytes32"}], "name": "uploadScore", "outputs": [], "stateMutability": "nonpayable", "type": "function"}]'  # noqa: E501

# Private
REDIS_HOST = os.environ['HEROKU_REDIS_HOST']
REDIS_PORT = os.environ['HEROKU_REDIS_PORT']
REDIS_PASSWORD = os.environ['HEROKU_REDIS_PASSWORD']
PRIV = os.environ['PRIVATE_KEY_0x2048']
INFURA_PROJECT_ID = os.environ['INFURA_PROJECT_ID']
INFURA_PROJECT_SECRET = os.environ['INFURA_PROJECT_SECRET']
