export const WELCOME = 'WELCOME';
export const PROMPT_PAYMENT = 'PROMPT_PAYMENT';
export const WAITING = 'WAITING';
export const METAMASK_ERROR = 'METAMASK_ERROR';
export const FETCH_PAYMENT_CODE_ERROR = 'FETCH_PAYMENT_CODE_ERROR';
export const PAYMENT_CONFIRMATION_ERROR = 'PAYMENT_CONFIRMATION_ERROR';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
